language: node_js
cache:
  directories:
    - node_modules
    - ~/.npm
node_js:
  - '18'
git:
  depth: 3
script:
  - yarn test
notifications:
  email:
      recipients:
        - julyluna10@gmail.com
      on_success: always
      on_failure: always
deploy:
  provide: heroku
  skip-cleanup: true
  keep-history: true
  api_key: de63704f-cde6-4771-98d4-1523e8e998ad
  app: ic-nodejs
  on:
    repo: julyluna10/Integraci-n-continua
